ALTER TABLE usuarios
ADD COLUMN senha VARCHAR(100),
ADD COLUMN registrado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
